name: base
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - blosc=1.21.3
  - boltons=23.0.0
  - boost-cpp=1.73.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.0
  - ca-certificates=2023.08.22
  - cairo=1.16.0
  - certifi=2023.7.22
  - cffi=1.15.1
  - cfitsio=3.470
  - charset-normalizer=2.0.4
  - conda=23.5.2
  - conda-content-trust=0.1.3
  - conda-libmamba-solver=23.5.0
  - conda-package-handling=2.1.0
  - conda-package-streaming=0.8.0
  - cryptography=39.0.1
  - expat=2.5.0
  - fmt=9.1.0
  - fontconfig=2.14.1
  - freetype=2.12.1
  - freexl=1.0.6
  - gdal=3.6.2
  - geos=3.8.0
  - geotiff=1.7.0
  - giflib=5.2.1
  - glib=2.69.1
  - hdf4=4.2.13
  - hdf5=1.12.1
  - icu=58.2
  - idna=3.4
  - intel-openmp=2023.1.0
  - jpeg=9e
  - json-c=0.16
  - jsonpatch=1.32
  - jsonpointer=2.1
  - kealib=1.5.0
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libarchive=3.6.2
  - libboost=1.73.0
  - libcurl=8.1.1
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgdal=3.6.2
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libkml=1.3.0
  - libmamba=1.4.1
  - libmambapy=1.4.1
  - libnetcdf=4.8.1
  - libnghttp2=1.52.0
  - libpng=1.6.39
  - libpq=12.15
  - libsolv=0.7.24
  - libspatialite=4.3.0a
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.10.3
  - libzip=1.8.0
  - lz4-c=1.9.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - ncurses=6.4
  - nspr=4.35
  - nss=3.89.1
  - numpy=1.26.0
  - numpy-base=1.26.0
  - openjpeg=2.4.0
  - openssl=3.0.11
  - packaging=23.0
  - pcre=8.45
  - pcre2=10.42
  - pip=23.1.2
  - pixman=0.40.0
  - pluggy=1.0.0
  - poppler=22.12.0
  - poppler-data=0.4.11
  - proj=6.2.1
  - pybind11-abi=4
  - pycosat=0.6.4
  - pycparser=2.21
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.11.4
  - qhull=2020.2
  - readline=8.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - ruamel.yaml=0.17.21
  - setuptools=67.8.0
  - six=1.16.0
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tiledb=2.3.3
  - tk=8.6.12
  - toolz=0.12.0
  - tqdm=4.65.0
  - uriparser=0.9.7
  - urllib3=1.26.16
  - wheel=0.38.4
  - xerces-c=3.2.4
  - xz=5.4.2
  - yaml-cpp=0.7.0
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.5
  - pip:
      - absl-py==2.0.0
      - anyio==4.0.0
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.0
      - astunparse==1.6.3
      - async-lru==2.0.4
      - attrs==23.1.0
      - babel==2.13.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - bleach==6.1.0
      - cachetools==5.3.1
      - click==8.1.7
      - comm==0.1.4
      - contourpy==1.1.1
      - cycler==0.12.1
      - debugpy==1.8.0
      - decorator==5.1.1
      - defusedxml==0.7.1
      - docker-pycreds==0.4.0
      - executing==2.0.0
      - fastjsonschema==2.18.1
      - filelock==3.12.4
      - flatbuffers==23.5.26
      - fonttools==4.43.1
      - fqdn==1.5.1
      - fsspec==2023.9.2
      - gast==0.5.4
      - gitdb==4.0.10
      - gitpython==3.1.37
      - google-auth==2.23.3
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.59.0
      - h5py==3.10.0
      - imageio==2.31.5
      - ipykernel==6.25.2
      - ipython==8.16.1
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.1
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.2
      - joblib==1.3.2
      - json5==0.9.14
      - jsonschema==4.19.1
      - jsonschema-specifications==2023.7.1
      - jupyter==1.0.0
      - jupyter-client==8.3.1
      - jupyter-console==6.6.3
      - jupyter-core==5.4.0
      - jupyter-events==0.7.0
      - jupyter-lsp==2.2.0
      - jupyter-server==2.7.3
      - jupyter-server-terminals==0.4.4
      - jupyterlab==4.0.6
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.25.0
      - jupyterlab-widgets==3.0.9
      - keras==2.14.0
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - libclang==16.0.6
      - markdown==3.5
      - markupsafe==2.1.3
      - matplotlib==3.8.0
      - matplotlib-inline==0.1.6
      - mistune==3.0.2
      - ml-dtypes==0.2.0
      - mpmath==1.3.0
      - nbclient==0.8.0
      - nbconvert==7.9.2
      - nbformat==5.9.2
      - nest-asyncio==1.5.8
      - networkx==3.1
      - notebook==7.0.4
      - notebook-shim==0.2.3
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.2.140
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - opencv-python==4.8.1.78
      - opt-einsum==3.3.0
      - overrides==7.4.0
      - pandas==2.1.1
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pathtools==0.1.2
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==10.0.1
      - platformdirs==3.11.0
      - prometheus-client==0.17.1
      - prompt-toolkit==3.0.39
      - protobuf==4.24.4
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py-cpuinfo==9.0.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pygments==2.16.1
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - qtconsole==5.4.4
      - qtpy==2.4.0
      - referencing==0.30.2
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.10.4
      - rsa==4.9
      - scikit-image==0.22.0
      - scikit-learn==1.3.1
      - scipy==1.11.3
      - seaborn==0.13.0
      - send2trash==1.8.2
      - sentry-sdk==1.31.0
      - setproctitle==1.3.3
      - smmap==5.0.1
      - sniffio==1.3.0
      - soupsieve==2.5
      - stack-data==0.6.3
      - sympy==1.12
      - tensorboard==2.14.1
      - tensorboard-data-server==0.7.1
      - tensorflow==2.14.0
      - tensorflow-estimator==2.14.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - termcolor==2.3.0
      - terminado==0.17.1
      - thop==0.1.1-2209072238
      - threadpoolctl==3.2.0
      - tifffile==2023.9.26
      - tinycss2==1.2.1
      - torch==2.1.0
      - torchaudio==2.1.0
      - torchvision==0.16.0
      - tornado==6.3.3
      - traitlets==5.11.2
      - triton==2.1.0
      - types-python-dateutil==2.8.19.14
      - typing-extensions==4.8.0
      - tzdata==2023.3
      - ultralytics==8.0.186
      - uri-template==1.3.0
      - wandb==0.15.12
      - wcwidth==0.2.8
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.6.4
      - werkzeug==3.0.0
      - widgetsnbextension==4.0.9
      - wrapt==1.14.1
prefix: /root/miniconda3
